" install pathogen:
" mkdir -p ~/.vim/autoload ~/.vim/bundle; \
" curl -Sso ~/.vim/autoload/pathogen.vim  \
"     https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim
"
" install nerdtree:
" cd ~/.vim/bundle
" git clone https://github.com/scrooloose/nerdtree.git
"
" install taglist:
" cd ~/.vim/bundle
" git clone https://github.com/vim-scripts/taglist.vim.git taglist 

set nocompatible

execute pathogen#infect()
syntax on
filetype plugin indent on
set number
set fileencodings=utf8,gbk,cp936
set fileencoding=utf8
set fileformats=unix,dos
set fileformat=unix
set expandtab
set tabstop=4
set shiftwidth=4
set backspace=indent,eol,start
set colorcolumn=80
set cindent
set bg=dark
set hlsearch
set ruler
set showmode
set nolinebreak

autocmd BufWrite * execute ":%s/ *$//"

map <F3> :NERDTreeToggle<CR>
map <C-h> <C-w>h
map <C-l> <C-w>l
imap <C-h> <left>
imap <C-j> <down>
imap <C-k> <up>
imap <C-l> <right>

let Tlist_Use_Right_Window=1
map <F4> :Tlist<CR>
