" install pathogen:
" mkdir -p ~/.vim/autoload ~/.vim/bundle; \
" curl -Sso ~/.vim/autoload/pathogen.vim  \
"     https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim
"
" install nerdtree:
" cd ~/.vim/bundle
" git clone https://github.com/scrooloose/nerdtree.git
"
" install taglist:
" cd ~/.vim/bundle
" git clone https://github.com/vim-scripts/taglist.vim.git taglist
"
" install a.vim:
" cd ~/.vim/bundle
" git clone https://github.com/vim-scripts/a.vim.git
"
" install minibufexpl
" cd ~/.vim/bundle
" git clone https://github.com/fholgado/minibufexpl.vim.git
"
" install indentLine
" cd ~/.vim/bundle
" git clone https://github.com/Yggdroot/indentLine.git

set nocompatible

execute pathogen#infect()
syntax on
filetype plugin indent on
set number
set ruler
language message en_US.UTF-8
set fileencodings=utf8,gbk,cp936
set fileencoding=utf8
set fileformats=unix,dos
set fileformat=unix
set expandtab
set tabstop=4
set shiftwidth=4
set backspace=indent,eol,start
set colorcolumn=80
set smartindent
set bg=dark
set hlsearch
set ruler
set showmode
set nolinebreak
colorscheme desert

map <F2> :MBEToggle<CR>
map <C-x> :w<CR>:MBEbd<CR>

map <F3> :NERDTreeToggle<CR>

map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l
imap <C-h> <left>
imap <C-j> <down>
imap <C-k> <up>
imap <C-l> <right>

let Tlist_Use_Right_Window=1
map <F4> :Tlist<CR>

map <F12> :A<CR>

" 尾部空格删除
autocmd BufWrite * execute ":mark z"
autocmd BufWrite * execute ":%s/ *$//"
autocmd BufWrite * execute "'z"

" 括号匹配
inoremap ( ()<LEFT>
inoremap [ []<LEFT>
inoremap { {}<LEFT>

" 自动检测文件类型
filetype on
filetype plugin on
autocmd FileType html source ~/.vim/myvim/html.vim
autocmd FileType js source ~/.vim/myvim/js.vim
autocmd FileType xml source ~/.vim/myvim/xml.vim
autocmd FileType c,cc,cpp,cxx,php,py,lua,sh,java,txt,go source ~/.vim/myvim/other.vim

" 获取当前路径，将$HOME转化为~
function! CurDir()
    let curdir = substitute(getcwd(), $HOME, "~", "g")
    return curdir
endfunction

" 状态栏
set laststatus=2      " 总是显示状态栏
highlight StatusLine cterm=bold ctermfg=yellow ctermbg=blue
" set statusline=[%n]\ %f%m%r%h\ \|\ \ pwd:\ %{CurDir()}\ \ \|%=\|\ %l,%c\ %p%%\ \|\ ascii=%b,hex=%b%{((&fenc==\"\")?\"\":\"\ \|\ \".&fenc)}\ \|\ %{$USER}@%{hostname()}

let g:indentLine_char = '┊'
let g:indentLine_color_term = 1
